//
//  ID3FrameConfiguration.swift
//
//  Created by Fabrizio Duroni on 20/02/2018.
//  2018 Fabrizio Duroni.
//

import Foundation

enum FrameType: String, Equatable {
    case Album = "album"
    case AlbumArtist = "albumArtist"
    case Arranger = "arranger"
    case Artist = "artist"
    case ArtistUrl = "artistUrl"
    case AudioFileUrl = "audioFileUrl"
    case AudioSourceUrl = "audioSourceUrl"
    case BPM = "bpm"
    case Comment = "comment"
    case Composer = "composer"
    case Conductor = "conductor"
    case ContentGroup = "contentGroup"
    case Copyright = "copyright"
    case CopyrightUrl = "copyrightUrl"
    case DiscPosition = "discPosition"
    case EncodedBy = "encodedBy"
    case EncoderSettings = "encoderSettings"
    case FileOwner = "fileOwner"
    case FileType = "fileType"
    case Genre = "genre"
    case InitialKey = "initialKey"
    case InvolvedPeople = "involvedPeople"
    case ISRC = "isrc"
    case Language = "language"
    case Length = "length"
    case Lyricist = "lyricist"
    case Mood = "Mood"
    case MusicianCredits = "musicianCredits"
    case OriginalAlbum = "originalAlbum"
    case OriginalArtist = "originalArtist"
    case OriginalYear = "originalYear"
    case OriginalFilename = "originalFilename"
    case OriginalLyricist = "originalLyricist"
    case PlaylistDelay = "playlistDelay"
    case Publisher = "publisher"
    case PublisherUrl = "publisherUrl"
    case RadioStation = "radioStation"
    case RadioStationOwner = "radioStationOwner"
    case RadioStationUrl = "radioStationUrl"
    case SetSubtitle = "setSubtitle"
    case SortAlbum = "sortAlbum"
    case SortAlbumArtist = "sortAlbumArtist"
    case SortArtist = "sortArtist"
    case SortComposer = "sortComposer"
    case SortPerformer = "sortPerformer"
    case SortTitle = "sortTitle"
    case Subtitle = "subtitle"
    case Title = "title"
    case TrackPosition = "trackPosition"
    case UnsyncedLyrics = "unsyncedLyrics"
    case UserDefinedTextInformation = "userDefinedTextInformation"
    case UserDefinedUrl = "userDefinedUrl"
    case RecordingDayMonth = "recordingDayMonth"
    case RecordingYear = "recordingYear"
    case RecordingHourMinute = "recordingHourMinute"
    case RecordingDateTime = "recodingDateTime"
    case AttachedPicture = "artwork"
    case iTunesCompilation = "compilation"
    case iTunesGrouping = "iTunesGrouping"
    case iTunesMovementCount = "iTunesMovementCount"
    case iTunesMovementIndex = "iTunesMovementIndex"
    case iTunesMovementName = "iTunesMovementName"
    case iTunesPodcastCategory = "iTunesPodcastCategory"
    case iTunesPodcastDescription = "iTunesPodcastDescription"
    case iTunesPodcastID = "iTunesPodcastID"
    case iTunesPodcastKeywords = "iTunesPodcastKeywords"
    case iTunesPodcastUrl = "iTunesPodcastUrl"
    case Invalid = ""
    
    static func ==(lhs: FrameType, rhs: FrameType) -> Bool {
        return lhs.rawValue == rhs.rawValue
    }
}
