//
//  ID3Language.swift
//  ID3TagEditor"
//
//  Created by Nolaine Crusher on 3/5/20.
//  Copyright © 2020 Fabrizio Duroni. All rights reserved.
//

import Foundation

public enum ID3Language: String, Equatable {
    
    case cnr = "Montenegrin"
    case zgh = "Standard Moroccan Tamazight"
    case hmn = "Hmong; Mong"
    case bih = "Bihari languages"
    case him = "Himachali languages; Western Pahari languages"
    case afa = "Afro-Asiatic languages"
    case apa = "Apache languages"
    case art = "Artificial languages"
    case bai = "Bamileke languages"
    case bat = "Baltic languages"
    case ber = "Berber languages"
    case bnt = "Bantu languages"
    case cai = "Central American Indian languages"
    case cau = "Caucasian languages"
    case cel = "Celtic languages"
    case cpe = "Creoles and pidgins, English based"
    case cpf = "Creoles and pidgins, French-based"
    case cpp = "Creoles and pidgins, Portuguese-based"
    case crp = "Creoles and pidgins"
    case cus = "Cushitic languages"
    case dra = "Dravidian languages"
    case fiu = "Finno-Ugrian languages"
    case gem = "Germanic languages"
    case inc = "Indic languages"
    case ine = "Indo-European languages"
    case ira = "Iranian languages"
    case iro = "Iroquoian languages"
    case khi = "Khoisan languages"
    case map = "Austronesian languages"
    case mkh = "Mon-Khmer languages"
    case nai = "North American Indian languages"
    case nic = "Niger-Kordofanian languages"
    case oto = "Otomian languages"
    case paa = "Papuan languages"
    case phi = "Philippine languages"
    case pra = "Prakrit languages"
    case roa = "Romance languages"
    case sai = "South American Indian languages"
    case sal = "Salishan languages"
    case sem = "Semitic languages"
    case sit = "Sino-Tibetan languages"
    case sla = "Slavic languages"
    case smi = "Sami languages"
    case ssa = "Nilo-Saharan languages"
    case tai = "Tai languages"
    case tut = "Altaic languages"
    case wak = "Wakashan languages"
    case mol = "Moldavian; Moldovan"
    case kho = "Khotanese; Sakan"
    case oci = "Occitan (post 1500)"
    case pro = "Provençal, Old (to 1500);Occitan, Old (to 1500)"
    case wal = "Wolaitta; Wolaytta"
    case srp = "Serbian"
    case hrv = "Croatian"
    case zxx = "No linguistic content; Not applicable"
    case gsw = "Swiss German; Alemannic; Alsatian"
    case pus = "Pushto; Pashto"
    case ast = "Asturian; Bable; Leonese; Asturleonese"
    case bej = "Beja; Bedawiyet"
    case chp = "Chipewyan; Dene Suline"
    case iii = "Sichuan Yi; Nuosu"
    case ile = "Interlingue; Occidental"
    case pam = "Pampanga; Kapampangan"
    case zbl = "Blissymbols; Blissymbolics; Bliss"
    case mis = "Uncoded languages"
    case arc = "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"
    case syc = "Classical Syriac"
    case bin = "Bini; Edo"
    case car = "Galibi Carib"
    case bad = "Banda languages"
    case btk = "Batak languages"
    case day = "Land Dayak languages"
    case ijo = "Ijo languages"
    case kar = "Karen languages"
    case kro = "Kru languages"
    case nah = "Nahuatl languages"
    case son = "Songhai languages"
    case srn = "Sranan Tongo"
    case znd = "Zande languages"
    case kac = "Kachin; Jingpho"
    case khm = "Central Khmer"
    case arn = "Mapudungun; Mapuche"
    case rar = "Rarotongan; Cook Islands Maori"
    case roh = "Romansh"
    case kir = "Kirghiz; Kyrgyz"
    case zza = "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"
    case div = "Divehi; Dhivehi; Maldivian"
    case nqo = "N'Ko"
    case krl = "Karelian"
    case frs = "Eastern Frisian"
    case fry = "Western Frisian"
    case anp = "Angika"
    case frr = "Northern Frisian"
    case rup = "Aromanian; Arumanian; Macedo-Romanian"
    case ain = "Ainu"
    case glg = "Galician"
    case alt = "Southern Altai"
    case xal = "Kalmyk; Oirat"
    case mic = "Mi'kmaq; Micmac"
    case nso = "Pedi; Sepedi; Northern Sotho"
    case sin = "Sinhala; Sinhalese"
    case fil = "Filipino; Pilipino"
    case mwl = "Mirandese"
    case scn = "Sicilian"
    case nwc = "Classical Newari; Old Newari; Classical Nepal Bhasa"
    case tlh = "Klingon; tlhIngan-Hol"
    case byn = "Blin; Bilin"
    case jbo = "Lojban"
    case dsb = "Lower Sorbian"
    case hsb = "Upper Sorbian"
    case csb = "Kashubian"
    case crh = "Crimean Tatar; Crimean Turkish"
    case ady = "Adyghe; Adygei"
    case krc = "Karachay-Balkar"
    case mdf = "Moksha"
    case myv = "Erzya"
    case udm = "Udmurt"
    case dar = "Dargwa"
    case inh = "Ingush"
    case nog = "Nogai"
    case hat = "Haitian; Haitian Creole"
    case kbd = "Kabardian"
    case arg = "Aragonese"
    case lim = "Limburgan; Limburger; Limburgish"
    case nap = "Neapolitan"
    case sma = "Southern Sami"
    case smj = "Lule Sami"
    case smn = "Inari Sami"
    case sms = "Skolt Sami"
    case wln = "Walloon"
    case ido = "Ido"
    case tup = "Tupi languages"
    case jav = "Javanese"
    case nbl = "Ndebele, South; South Ndebele"
    case nde = "Ndebele, North; North Ndebele"
    case nds = "Low German; Low Saxon; German, Low; Saxon, Low"
    case ave = "Avestan"
    case bam = "Bambara"
    case bos = "Bosnian"
    case cha = "Chamorro"
    case che = "Chechen"
    case chu = "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"
    case chv = "Chuvash"
    case her = "Herero"
    case hmo = "Hiri Motu"
    case kik = "Kikuyu; Gikuyu"
    case kom = "Komi"
    case kua = "Kuanyama; Kwanyama"
    case mah = "Marshallese"
    case mnc = "Manchu"
    case nav = "Navajo; Navaho"
    case ndo = "Ndonga"
    case nno = "Norwegian Nynorsk; Nynorsk, Norwegian"
    case nob = "Bokmål, Norwegian; Norwegian Bokmål"
    case nya = "Chichewa; Chewa; Nyanja"
    case oss = "Ossetian; Ossetic"
    case pli = "Pali"
    case sgn = "Sign Languages"
    case sme = "Northern Sami"
    case srd = "Sardinian"
    case tah = "Tahitian"
    case aka = "Akan"
    case ava = "Avaric"
    case cre = "Cree"
    case ewe = "Ewe"
    case ful = "Fulah"
    case ibo = "Igbo"
    case kau = "Kanuri"
    case kon = "Kongo"
    case lub = "Luba-Katanga"
    case lug = "Ganda"
    case oji = "Ojibwa"
    case ven = "Venda"
    case cor = "Cornish"
    case glv = "Manx"
    case ltz = "Luxembourgish; Letzeburgesch"
    case heb = "Hebrew"
    case iku = "Inuktitut"
    case ind = "Indonesian"
    case uig = "Uighur; Uyghur"
    case yid = "Yiddish"
    case zha = "Zhuang; Chuang"
    
    /**
     Compare two ID3Language.

     - parameter lhs: left side of compare operation.
     - parameter rhs: right side of compare operation.

     - returns: true if the language values are the same, else false.
     */
    public static func ==(lhs: ID3Language, rhs: ID3Language) -> Bool {
        return lhs.rawValue == rhs.rawValue
    }

}
