name: Build tvOS

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 16 15 * *'

jobs:
  build:      
    name: Build tvOS
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build tvOS framework
        run: |
          set -o pipefail && xcodebuild -project ID3TagEditor.xcodeproj -scheme "ID3TagEditor tvOS" clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=tvOS Simulator,name=Apple TV,OS=latest" -skipPackagePluginValidation | xcpretty
      - name: Build tvOS Demo
        run: | 
          set -o pipefail && xcodebuild -project Demo/Demo.xcodeproj -scheme "Demo tvOS"  clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=tvOS Simulator,name=Apple TV,OS=latest" -skipPackagePluginValidation | xcpretty
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
